name: Latest commit message made by user
on:
  push:
    branches:
      - main
  create:
    schedule:
      # Runs every 6 hours
      - cron: '* */6 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-last-commit:
    name: Update this repo's README with latest commit made
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: estarossa0/readme-last-commit@master
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
